// Game catalog for YSY Softworks - real cover art URLs pulled from ysysoftworks.net.
// Fabricated metadata (genre, release, tagline, description) is filled in for layout purposes;
// these are placeholders - replace with real marketing copy when available.

window.YSY_GAMES = [
  {
    slug: "insurgence-last-wishes",
    title: "Insurgence - Last Wishes",
    cover: "https://lh3.googleusercontent.com/sitesv/AA5AbUBZ2Z7Zkfz8udOoyneargDOS4-XwQ0Y1w2vfcrL8jTfhv8ZQUw5KA5FjKFjHDk5MQ6a9YxDqAjw8JLIs2vJcXLLHu5nA-ZsoyJPu-T1E-rrh1xEzZasDvqVhCprQheN36V8IHYxVtzCFdMsC0sk87_SApebmbZo9Hn97cxtL4cRs7_pH13xrtSIHxQ=w1280",
    genre: "Tactical RPG",
    platforms: ["PC", "Steam"],
    status: "Out Now",
    release: "2025-11-14",
    featured: true,
    featuredOrder: 1,
    description: "Close the Insurgence saga with Last Wishes - a turn-based tactical odyssey where every fallen comrade rewrites the battlefield.",
  },
  {
    slug: "transcendence-legacy-voidswept",
    title: "Transcendence Legacy - Voidswept",
    cover: "https://lh3.googleusercontent.com/sitesv/AA5AbUC5ldXj0M3NUr2wC64BE915jR6YSBPQfwcGpkkqsrj_c5eZMg1h5lH8EVTTD-T2EqvVp-asaRyJbFTuEj7BOpVP1bVnBrLR59aHqL29YDlnb0u7WyXOOHtydV953hy1PviY_mMp-nZZGmDvTwzLK6GfO3POBbfJig2D8YuZqV8O4600sbWbqW9RvelDlwE2U3h8wKpPE8-kY0ULb7-6zIlne2bi1ODb3viH=w1280",
    genre: "Action RPG",
    platforms: ["PC", "Steam"],
    status: "Out Now",
    release: "2025-09-02",
    featured: true,
    featuredOrder: 2,
    description: "A spellbound action-RPG set in a shattered cosmos, where every constellation hides a lost piece of memory.",
  },
  {
    slug: "bail-force",
    title: "Bail Force",
    cover: "https://lh3.googleusercontent.com/sitesv/AA5AbUClNHeocs0TCa2q4GqozPdxQikMS5isYWsUZlPFJdJR2F3sCVMT9gJrick57xibN9KNVzghWNOtHpC2MkeFciDryPl1ocY-OYDuErp6Vjllyj58dikEl3NMPk7FcpckL1tpTPA7Mgq46Y0KkKEDulueXIlHMNegkqY2E1_QsELdjcid9AN6DL-eIPk=w1280",
    genre: "Action",
    platforms: ["PC", "Steam"],
    status: "Out Now",
    release: "2025-07-18",
    featured: true,
    featuredOrder: 3,
    description: "Chase rogues across a cyberlit metropolis in a combat-forward arcade shooter with anime-style key art.",
  },
  {
    slug: "crownless-abyss",
    title: "Crownless Abyss",
    cover: "https://lh3.googleusercontent.com/sitesv/AA5AbUB9E47Xs8mFP3mJ68aJiOqaTHGPcfLWPojNobMY4fZCIB-N51u1bLFeSUlqe8HYFFFcLD0fHz6XUxVeL7_bBaVNATuSBRVRlCtUBoi-g4UMJshU4Ub3q7KAcJwNdVoVnHsEiyMEuKdCeqbZb9dQTHHRN9In2c1OTzEdkuDrs48uiz5uJRGM8Nz-075bDQIt1fnGhbMBps-1PtjlSY2THX1r93VKI7FtLnjluRE=w1280",
    genre: "Dark Fantasy RPG",
    platforms: ["PC", "Steam"],
    status: "Coming Soon",
    release: "2026-06-05",
    tagline: "The throne is empty. The dark is not.",
    description: "A descent into a ruined kingdom where every choice carves a new scar onto the world below.",
  },
  {
    slug: "czar-decision",
    title: "CZAR - Decision",
    cover: "https://lh3.googleusercontent.com/sitesv/AA5AbUCxPzdRoYqPJBqEpBDixt8sXL4wmFKYF-_s8Anm4FwPbpNZs5xb78Z0djzMfRwnHg517UmC-vQsTsvu7h7i1VPrOX5TYxzlD0Ce7B9txF8WHrDYicZ5W2ECQjGmYQD5kDkjmuvW8ybUN4z6XOvdm0R8J1f3I2dfiyVytP1Iw8ZOiNvUTuJ3IYHpuCo=w1280",
    genre: "Strategy",
    platforms: ["PC", "Steam"],
    status: "Out Now",
    release: "2024-10-20",
    tagline: "Rule with the weight of every choice.",
    description: "A narrative-heavy strategy sim where each decision reshapes the map and the people in it.",
  },

  {
    slug: "ed-archivist-curse",
    title: "Eremidia - Archivist Curse",
    cover: "https://lh3.googleusercontent.com/sitesv/AA5AbUBnMtqxMcFjc45lZIrXJbFRm2ePLdkYn_VxAC9BOLOOIFAZlFAsqG3R4N1TljL6L-j8R0VHZc4OedsyIgOmDdv_L-XXEbA6R0_B-sdhMzb3UPkLkn0Eu4WEfMpfE8FxsbpuTHmJ9S_XO9rL-haHYp0W0xGC6CYFLJmw3i9vzVRitQ5jzRX8t2_rYE1koo1bcjMpWfWqWBPDbHx2IkfTM_yNPju_L84pG40P3Mg=w1280",
    genre: "JRPG",
    platforms: ["PC", "Steam"],
    status: "Out Now",
    release: "2024-05-03",
    tagline: "Every book remembers who read it last.",
    description: "Classic JRPG exploration threaded with a librarian's deep, uneasy magic.",
  },
  {
    slug: "fragmented-memories-arc-one",
    title: "Fragmented Memories - Arc One",
    cover: "https://lh3.googleusercontent.com/sitesv/AA5AbUCh1jSSWageWh52SSGruLLDtrCSaeGF2VNTox-rCGLfQ7-Wi0nagqg9gcqP2KoiTlOOx7qzR4cyXxYd0_-85jL457teFg9EvSgof8nSeo0ewfFr25Rhe4fQZFsNDqkgm5hF_XiuKkvSC6urOV8zyhC4JfjuC1U6aNUzWz9IIKtTk1arFX8IuSJL2a1Mu3a7IRni1JYqzPawByoq_OGJoyJORd5Cmcd5HShP=w1280",
    genre: "Visual Novel",
    platforms: ["PC", "Steam"],
    status: "Out Now",
    release: "2024-02-14",
    tagline: "Piece the past, one shard at a time.",
    description: "A branching visual novel that asks whether remembering is the same as forgiving.",
  },
  {
    slug: "insurgence-chains-of-renegade",
    title: "Insurgence - Chains of Renegade",
    cover: "https://lh3.googleusercontent.com/sitesv/AA5AbUCqFG9SVUrEWkeFqp95vjlKkSbS8MI5tTu_jNTio1l7pG1HJvhF2PsKNgS7yndfqZzlGP5_P6956YmjjhZXrYVk5TVrn0sTvh7wo2dNCcv7D9D8ExzKQsUd35sevhxOP2PLrNSDJnMX2RxW08DEIdwZ4OybdfQNLaJ8YzSf9CWj6lv6kbdsXCN_=w1280",
    genre: "Tactical RPG",
    platforms: ["PC", "Steam"],
    status: "Out Now",
    release: "2023-11-09",
    tagline: "No flag. No honor. Only fight.",
    description: "The first Insurgence chapter - where mercenaries become a movement.",
  },
  {
    slug: "insurgence-second-assault",
    title: "Insurgence - Second Assault",
    cover: "https://lh3.googleusercontent.com/sitesv/AA5AbUCOeNfU_Fyq7mSXNGji3RDD5qy4QgTtlXemzBxZAYWDAjsUUXw0UhY3LZ4buDST31Octa-D6LDcaKsRHA_yahXbuVT3Enn11SkZ7NNgp7hoYgHjS_Z37RK66PBb_Htj-6R8Wco7natD5OU_WX1D0WJa67ngGpIo08ueS_splmRZxvIxyXLIrWPe=w1280",
    genre: "Tactical RPG",
    platforms: ["PC", "Steam"],
    status: "Out Now",
    release: "2024-06-28",
    tagline: "Regroup. Reload. Return fire.",
    description: "The middle chapter - heavier squads, bigger gambits, louder guns.",
  },
  {
    slug: "reach-for-an-angel",
    title: "Reach for an Angel",
    cover: "https://lh3.googleusercontent.com/sitesv/AA5AbUBjif5z1pCK18Vi1qUbKZEEGVqQ1gRVoJY_QbIcBwhBMr1mjS3brXZQZEK1gzrVN2MqtNz6wiNCBNiQnHRytqD7FmiiRrGVLvbKFQt7crm8EUsHndzl8FYWzbbdcUI7LOoLZm4Iw2_4xe3pE_Qc0MGtHOuhSEDca_kwu16p3NgdEKoPk-gav9GYpnQi-cdPdtX0htGpPgnRpKUWeH7dIiV-9_CgX_BUJTgu=w1280",
    genre: "Romance / VN",
    platforms: ["PC", "Steam"],
    status: "Out Now",
    release: "2023-07-07",
    tagline: "Fall slowly. Rise on purpose.",
    description: "A summer-bright romance VN with hand-painted skies and quietly devastating choices.",
  },
  {
    slug: "ruins-of-dawnseeker",
    title: "Ruins of Dawnseeker",
    cover: "https://lh3.googleusercontent.com/sitesv/AA5AbUBWVavvSKJg2ohCzLN9VF6pGZhUgCyNxGhKcw7qrxg5z_8Le3Uhd3veiA1NrOGeaZztSukRp3MDabWNCQXn8y8WGlTs_HFixjan73BeZOC05zOMjzmIaSq18Sh5uSx_R27qXGSqgQE3dGnAGxbn7nO_pD5O16hwU_HkeXnRpTtdDfDKBkxvG19N=w1280",
    genre: "Roguelite",
    platforms: ["PC", "Steam"],
    status: "Early Access",
    release: "2025-04-22",
    tagline: "One more run toward the sun.",
    description: "A relic-hunting roguelite with gorgeous painterly vistas and ruthlessly clever enemies.",
  },
  {
    slug: "twilight-memoria-sun-moon",
    title: "Twilight Memoria - Sun & Moon",
    cover: "https://lh3.googleusercontent.com/sitesv/AA5AbUDUKI_92NQv0zc2WQVzV2R42m4wluuFGk-c2G4expzLcI5eCmiWswlk6Otaz7PJf1prTmEtgJTWiqq7nTS4RB5v60qnKYmyQDXQKlnEhaf6zwpj1qIrHF6VnZhZsfqPsAcHXewZREVBN2LBeU9kT7Zb9RxzvyYVaHBLdIIZakxqN0N7TeQR3_eb=w1280",
    genre: "RPG",
    platforms: ["PC", "Steam"],
    status: "Out Now",
    release: "2023-03-15",
    tagline: "Two skies. One horizon.",
    description: "A dual-perspective RPG where day and night write each other's stories.",
  },
  {
    slug: "twilight-memoria-freedoom",
    title: "Twilight Memoria - Freedom",
    cover: "https://lh3.googleusercontent.com/sitesv/AA5AbUAPK_ePfodNoT20xkY45R8-5wYGmRjqhhVu0k249E1H5lHiXxP71t5tiVQlHvc_F0MczXKWZiBxHo9rn6zvHh0hazuqWNmq8i5g0-PEwVLRPxgTrr3lQK83udc6bs2P-sJ1hxoqzO7uUsm5mKGwWCaz-CluaqclxPPuF6JK3MFq0M-mawkU8nFRS49vZKh61zUCtVEeIV4ysx6b6y-UYLwg5jyjRSuvnhNvQUg=w1280",
    genre: "RPG",
    platforms: ["PC", "Steam"],
    status: "Coming Soon",
    release: "2026-03-20",
    tagline: "The sequel arrives at last light.",
    description: "The long-awaited second arc of Twilight Memoria - larger maps, deeper party mechanics.",
  },
  {
    slug: "your-shining-youth",
    title: "Your Shining Youth",
    cover: "https://lh3.googleusercontent.com/sitesv/AA5AbUA4jNNgtgrMyPn7V85Rx8TLU4CXRXwjwbTeaO0A9qBpxAw5Kj1SNayomOSJOYT24SbPd2Y0G-TfbsrR4kBA8VubqkjSEjhujQxlfvc_lIyx-IS7f8MrD3WPl9DrMEeTcGSxtQ8dO9C4g13X6S8X8ZaQF0hziK3KKhad8xyaCBls2mG9E1dTFZh-=w1280",
    genre: "Slice of Life",
    platforms: ["PC", "Steam"],
    status: "Out Now",
    release: "2023-04-01",
    tagline: "The flagship title.",
    description: "The studio's namesake - a school-days slice-of-life visual novel that started it all.",
  },
];

window.YSY_STUDIO = {
  name: "YSY Softworks",
  steam: "https://store.steampowered.com/publisher/ysysoftworks",
  twitter: "https://twitter.com/ysysoftworks",
  facebook: "https://www.facebook.com/ysysoftworks",
  copy: "Welcome to YSY Softworks! We're a global PC game developer & publisher focused on Japanese ACG culture, creating visually stunning anime-style games. Our mission is to provide engaging gameplay, beautiful graphics, and unique storylines that transport you to imaginative and immersive worlds. With a diverse range of games, we're constantly pushing the boundaries of what's possible in game development. Thank you for visiting, and we hope you enjoy our games!",
};
